### PR TITLE
build(uraft): Update boost functions to work with boost 1.87

### PR DESCRIPTION
**Pull request by uristdwarf**
Uraft was causing compilation errors with boost 1.87, as some backwards compatible stuff was removed in later versions. This fixes those issues by using library calls available in Boost 1.87 and earlier versions.

### CODE REVIEW

**Comment by aNeutrino** [comment]
@ralcolea we may need your help to run it against URAFT ansible e2e tests. Before we merge it.

**Comment by ralcolea** [comment]
> @ralcolea we may need your help to run it against URAFT ansible e2e tests. Before we merge it.

Sure, just let me know and I will gladly join you for testing :)

**Comment by uristdwarf** [comment]
Tests seem to work fine, so I think this is ready for review.

**Review by ralcolea — APPROVED** [review]
Great job, @uristdwarf! 👍
Nice **Boost** to uRaft 😄

File: src/uraft/main.cc [hunk 1]
```diff
@@ -236,7 +236,7 @@ int main(int argc, char **argv) {
 		server.set_options(opt);
 		makePidFile(pidfile);
 #if (BOOST_VERSION >= 104700)
```
Comment (rolysr) [inline src/uraft/main.cc:238]: Maybe this is a good opportunity to substitute `104700` by something describing what is available from that version that matters to our code.

File: src/uraft/uraft.cc [hunk 2]
```diff
@@ -1,5 +1,6 @@
 #include "common/platform.h"
 #include "uraft.h"
+#include <boost/lexical_cast.hpp>
```
Comment (rolysr) [inline src/uraft/uraft.cc]: Consider to separate these imports so that it could be separated by type as we do on there files, for instance:
```
#include "common/platform.h"

#include <boost/lexical_cast.hpp>

#include "uraft.h"
```

**Review by rolysr — APPROVED** [review]
LGTM. Consider my minor suggestions if applicable.

File: src/uraft/main.cc (hunk 1 above)
Comment (uristdwarf) [reply src/uraft/main.cc:238]: I think this is out of scope for now, but we need to review these ifdefs anyway in the future.
